apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubernetes.io/createdby: portworx-volume-dynamic-provisioner
    pv.kubernetes.io/bound-by-controller: "yes"
    pv.kubernetes.io/provisioned-by: kubernetes.io/portworx-volume
  name: shared-pv
  namespace: shared-volume
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: shared-pvc
    namespace: shared-test
  persistentVolumeReclaimPolicy: Retain
  storageClassName: portworx-shared-gp3
  volumeMode: Filesystem
