apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/portworx-volume
    volume.kubernetes.io/storage-provisioner: kubernetes.io/portworx-volume
  name: shared-pvc
  namespace: shared-volume
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 1Gi
    storageClassName: portworx-shared-gp3
    volumeMode: Filesystem
